// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vledcsokbtgfuangnwlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZWRjc29rYnRnZnVhbmdud2x0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODk2ODgsImV4cCI6MjA2MjI2NTY4OH0.4WDoDs_lwjm5Puw_xE6YECphU2hoP_gv818pnAS-ZoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);